name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: LaTeX compilation
      uses: dante-ev/latex-action@v0.2.0
      with:
        root_file: cs141.tex
        args: -bibtex -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -latexoption=-shell-escape -latexoption=-synctex=1

    - name: Upload cs141.pdf
      uses: actions/upload-artifact@v2
      with:
        name: cs141.pdf
        path: cs141.pdf
